spring:
  application:
    name: auth-service

server:
  port: 8992

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com:
      returnorder:
        managment: DEBUG