name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: vicgok/return-order-portal-app
          tags: latest
          registry: docker.io
          dockerfile: /Angular-Frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
