name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
      # steps to perform in job
    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: |
#             docker build --file Dockerfile --tag vicgok/return-order-portal-app:latest .
#       working-directory: ./Angular-Frontend


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Change working directory for anugular app
        run: |
        working-directory: ./Angular-Frontend
          
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: vicgok/return-order-portal-app:latest
       
