name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./Angular-Frontend
    
    
      # steps to perform in job
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
            working-directory: ./Angular-Frontend
            docker build --file Dockerfile --tag vicgok/return-order-portal-app:latest .

      
