name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code
        
      - name: Build docker images using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
            username: "${{ secrets.DOCKER_HUB_USERNAME }}"
            password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
            image_name: vicgok/return-order-portal-app
            image_tag: latest
            dockerfile: Angular-Frontend/Dockerfile       

